#!/usr/bin/env bash

# Inicio das funções

################################################################################
# Função para mostrar mensagem de erro
_MSG_ERRO_INFO() { clear ; whiptail --title "Erro" --msgbox "$1" 0 0 ; exit 20 ; }

################################################################################

# Exemplo de configuração
which multipath || apt install multipath-tools -y
ISCSI=$(find /etc -iname iscsid.conf)

sed -i 's/^node.startup.*/node.startup = manual/g'                                                  "$ISCSI" || _MSG_ERRO_INFO "Arquivo $ISCSI não encontrado"
sed -i 's/^node.session.timeo.replacement_timeout.*/node.session.timeo.replacement_timeout = 120/g' "$ISCSI" || _MSG_ERRO_INFO "Arquivo $ISCSI não encontrado"


if ! whiptail --title "Disco ISCSI" --yesno "Disco ISCSI já foi adicionado ao Cluster ou PVE" 10 50 ; then _MSG_ERRO_INFO "Favor adicionar o Disco" ; fi 

MPATH=$(/lib/udev/scsi_id -g -u -d /dev/sd[bcde]) || _MSG_ERRO_INFO "Erro ao executar scsi_is"

[[ $(wc -l "$MPATH") -eq 0 ]] || _MSG_ERRO_INFO "UID não informada"

multipath -a "$MPATH" || _MSG_ERRO_INFO "Erro ao executar multipath"

touch /etc/multipath.conf

cat > /etc/multipath.conf  << EOF

defaults {
        polling_interval        2
        path_selector           "round-robin 0"
        path_grouping_policy    multibus
        uid_attribute           ID_SERIAL
        rr_min_io               100
        failback                immediate
        no_path_retry           queue
        user_friendly_names     yes
}

multipaths {
  multipath {
        wwid "$MPATH"
        alias mpath0
  }
}

blacklist {
        wwid .*
}

blacklist_exceptions {
        wwid "$MPATH"
}
EOF

if whiptail --title "Aplicar Configurações" --yesno "Deseja reiniciar o servidor" 10 50 ; then reboot ; fi
